kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: kind
nodes:
  - role: control-plane
    extraPortMappings:
      - { containerPort: 30017, hostPort: 27017, listenAddress: "127.0.0.1", protocol: TCP }  # mongodb
      - { containerPort: 30672, hostPort: 5672,  listenAddress: "127.0.0.1", protocol: TCP }  # rabbitmq amqp
      - { containerPort: 31672, hostPort: 15672, listenAddress: "127.0.0.1", protocol: TCP }  # rabbitmq mgmt
      - { containerPort: 30543, hostPort: 5432,  listenAddress: "127.0.0.1", protocol: TCP }  # cratedb psql
      - { containerPort: 30420, hostPort: 4301,  listenAddress: "127.0.0.1", protocol: TCP }  # cratedb http
