version: '3.7'
networks:
  mongo-net:
  redis:
volumes:
  mongo-data0:
  mongo-data1:
  mongo-data2:
  crate-data1:
  crate-data2:
  crate-data3:

services:
  mongo-2.mongo:
    hostname: mongo-2.mongo
    container_name: mongo-2.mongo
    image: mongo:6.0
    command: bash -c "chmod 400 /data/file.key && /usr/bin/mongod --keyFile /data/file.key --replSet rs --journal --bind_ip_all" 
    ports:
    - "27018:27017"
    restart: always
    networks:
      - mongo-net
    volumes:
    - "./file.key:/data/file.key"
    - "mongo-data2:/data/db"

  mongo-1.mongo:
    hostname: mongo-1.mongo
    container_name: mongo-1.mongo
    image: mongo:6.0
    command: bash -c "chmod 400 /data/file.key && /usr/bin/mongod --keyFile /data/file.key --replSet rs --journal --bind_ip_all" 
    ports:
    - "27019:27017"
    restart: always
    networks:
      - mongo-net
    volumes:
    - "./file.key:/data/file.key"
    - "mongo-data1:/data/db"


  mongo-0.mongo:
    hostname: mongo-0.mongo
    container_name: mongo-0.mongo
    image: mongo:6.0
    command: bash -c "chmod 400 /data/file.key && /usr/bin/mongod --keyFile /data/file.key --replSet rs --journal --bind_ip_all" 
    ports:
    - "27017:27017"
    links:
    - mongo-1.mongo:mongo-1.mongo
    - mongo-2.mongo:mongo-2.mongo
    restart: always
    networks:
      - mongo-net
    volumes:
    - "./scripts/init-database.js:/scripts/init-database.js"
    - "./scripts/create-admin-user.js:/scripts/create-admin-user.js"
    - "./file.key:/data/file.key"
    - "mongo-data0:/data/db"

  redis:
    hostname: redis
    container_name: redis
    image: redis
    networks:
      - redis
    ports:
      - "6379:6379"
      
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.12-management   
    
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"
  cratedb01:
    hostname: cratedb01
    container_name: cratedb01
    image: crate:latest
    ports:
      - "4201:4200"
    volumes:
      - crate-data1:/data
    command: ["crate",
              "-Ccluster.name=crate-docker-cluster",
              "-Cnode.name=cratedb01",
              "-Cnode.data=true",
              "-Cnetwork.host=_site_",
              "-Cdiscovery.seed_hosts=cratedb02,cratedb03",
              "-Ccluster.initial_master_nodes=cratedb01,cratedb02,cratedb03",
              "-Cgateway.expected_data_nodes=3",
              "-Cgateway.recover_after_data_nodes=2"]
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    environment:
      - CRATE_HEAP_SIZE=1g

  cratedb02:
    hostname: cratedb02
    container_name: cratedb02
    image: crate:latest
    ports:
      - "4202:4200"
    volumes:
      - crate-data2:/data
    command: ["crate",
              "-Ccluster.name=crate-docker-cluster",
              "-Cnode.name=cratedb02",
              "-Cnode.data=true",
              "-Cnetwork.host=_site_",
              "-Cdiscovery.seed_hosts=cratedb01,cratedb03",
              "-Ccluster.initial_master_nodes=cratedb01,cratedb02,cratedb03",
              "-Cgateway.expected_data_nodes=3",
              "-Cgateway.recover_after_data_nodes=2"]
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    environment:
      - CRATE_HEAP_SIZE=1g

  cratedb03:
    hostname: cratedb03
    container_name: cratedb03
    image: crate:latest
    ports:
      - "4203:4200"
    volumes:
      - crate-data3:/data
    command: ["crate",
              "-Ccluster.name=crate-docker-cluster",
              "-Cnode.name=cratedb03",
              "-Cnode.data=true",
              "-Cnetwork.host=_site_",
              "-Cdiscovery.seed_hosts=cratedb01,cratedb02",
              "-Ccluster.initial_master_nodes=cratedb01,cratedb02,cratedb03",
              "-Cgateway.expected_data_nodes=3",
              "-Cgateway.recover_after_data_nodes=2"]
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    environment:
      - CRATE_HEAP_SIZE=1g