version: '3.7'
networks:
  mongo-net:
  redis:
volumes:
  mongo-data0:
  mongo-data1:
  mongo-data2:

services:
  mongo-2.mongo:
    hostname: mongo-2.mongo
    container_name: mongo-2.mongo
    image: mongo:6.0
    command: bash -c "chmod 400 /data/file.key && /usr/bin/mongod --keyFile /data/file.key --replSet rs --journal --bind_ip_all" 
    ports:
    - "27018:27017"
    restart: always
    networks:
      - mongo-net
    volumes:
    - "./file.key:/data/file.key"
    - "mongo-data2:/data/db"

  mongo-1.mongo:
    hostname: mongo-1.mongo
    container_name: mongo-1.mongo
    image: mongo:6.0
    command: bash -c "chmod 400 /data/file.key && /usr/bin/mongod --keyFile /data/file.key --replSet rs --journal --bind_ip_all" 
    ports:
    - "27019:27017"
    restart: always
    networks:
      - mongo-net
    volumes:
    - "./file.key:/data/file.key"
    - "mongo-data1:/data/db"


  mongo-0.mongo:
    hostname: mongo-0.mongo
    container_name: mongo-0.mongo
    image: mongo:6.0
    command: bash -c "chmod 400 /data/file.key && /usr/bin/mongod --keyFile /data/file.key --replSet rs --journal --bind_ip_all" 
    ports:
    - "27017:27017"
    links:
    - mongo-1.mongo:mongo-1.mongo
    - mongo-2.mongo:mongo-2.mongo
    restart: always
    networks:
      - mongo-net
    volumes:
    - "./scripts/init-database.js:/scripts/init-database.js"
    - "./scripts/create-admin-user.js:/scripts/create-admin-user.js"
    - "./file.key:/data/file.key"
    - "mongo-data0:/data/db"


  redis:
    hostname: redis
    container_name: redis
    image: redis
    networks:
      - redis
    ports:
      - "6379:6379"
      