name: Sync ESLint Config

on:
  push:
    branches:
      - main
    paths:
      - 'typescript/.eslintrc-global.json'

jobs:
  sync:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo:
        - name: 'meshmakers/octo-frontend-libraries'
          path: 'src/FrontendLibraries/ClientApp/'

    steps:
    - name: Checkout octo-tools repo
      uses: actions/checkout@v2
      with:
        path: octo-tools

    - name: Generate GitHub App token
      id: app-token
      uses: actions/create-github-app-token@v1
      with:
        app-id: ${{ secrets.APP_ID }}
        private-key: ${{ secrets.APP_PRIVATE_KEY }}
        owner: ${{ github.repository_owner }}

    - name: Checkout other repo
      uses: actions/checkout@v2
      with:
        repository: ${{ matrix.repo.name }}
        token: ${{ steps.app-token.outputs.token }}
        path: other-repo

    - name: Copy ESLint config
      run: cp octo-tools/typescript/.eslintrc-global.json other-repo/${{ matrix.repo.path }}.eslintrc-global.json

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ steps.app-token.outputs.token }}
        path: other-repo
        title: "Update ESLint config"
        body: "Automated sync of ESLint config from octo-tools"
        branch: "automated-eslint-update"
